name: Example workflow
on:
  workflow_dispatch
jobs:
  run-demo-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.GITHUB }}
    - name: Set up Python 3.7.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.8'
    - name: Run script that echo outputs
      run: python main.py
